export const FETCH_BREEDS_START = 'FETCH_BREEDS_START';
export const FETCH_BREEDS_SUCCESSFUL = 'FETCH_BREEDS_SUCCESSFUL';
export const FETCH_BREEDS_FAILED = 'FETCH_BREEDS_FAILED';
export const FETCH_SELECTED_START = 'FETCH_SELECTED_START';
export const FETCH_SELECTED_SUCCESSFUL = 'FETCH_SELECTED_SUCCESSFUL';
export const FETCH_SELECTED_FAILED = 'FETCH_SELECTED_FAILED';
